//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoMortalidad.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nofetal2017Entities : DbContext
    {
        public nofetal2017Entities()
            : base("name=nofetal2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_DEFUN_PREGUNTA> A_DEFUN_PREGUNTA { get; set; }
        public virtual DbSet<AREA_RES_PREGUNTA> AREA_RES_PREGUNTA { get; set; }
        public virtual DbSet<ASIS_MED_PREGUNTA> ASIS_MED_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT1_PREGUNTA> C_ANT1_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT12_PREGUNTA> C_ANT12_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT2_PREGUNTA> C_ANT2_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT22_PREGUNTA> C_ANT22_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT3_PREGUNTA> C_ANT3_PREGUNTA { get; set; }
        public virtual DbSet<C_ANT32_PREGUNTA> C_ANT32_PREGUNTA { get; set; }
        public virtual DbSet<C_BAS1_PREGUNTA> C_BAS1_PREGUNTA { get; set; }
        public virtual DbSet<C_DIR1_PREGUNTA> C_DIR1_PREGUNTA { get; set; }
        public virtual DbSet<C_DIR12_PREGUNTA> C_DIR12_PREGUNTA { get; set; }
        public virtual DbSet<C_MCM1_PREGUNTA> C_MCM1_PREGUNTA { get; set; }
        public virtual DbSet<C_MUERTE_PREGUNTA> C_MUERTE_PREGUNTA { get; set; }
        public virtual DbSet<C_MUERTEB_PREGUNTA> C_MUERTEB_PREGUNTA { get; set; }
        public virtual DbSet<C_MUERTEC_PREGUNTA> C_MUERTEC_PREGUNTA { get; set; }
        public virtual DbSet<C_MUERTED_PREGUNTA> C_MUERTED_PREGUNTA { get; set; }
        public virtual DbSet<C_MUERTEE_PREGUNTA> C_MUERTEE_PREGUNTA { get; set; }
        public virtual DbSet<C_PAT1_PREGUNTA> C_PAT1_PREGUNTA { get; set; }
        public virtual DbSet<C_PAT2_PREGUNTA> C_PAT2_PREGUNTA { get; set; }
        public virtual DbSet<CAU_HOMOL_PREGUNTA> CAU_HOMOL_PREGUNTA { get; set; }
        public virtual DbSet<CAUSA_666_PREGUNTA> CAUSA_666_PREGUNTA { get; set; }
        public virtual DbSet<COD_DPTO_PREGUNTA> COD_DPTO_PREGUNTA { get; set; }
        public virtual DbSet<COD_MUNIC_PREGUNTA> COD_MUNIC_PREGUNTA { get; set; }
        public virtual DbSet<CODMUNOC_PREGUNTA> CODMUNOC_PREGUNTA { get; set; }
        public virtual DbSet<CODMUNRE_PREGUNTA> CODMUNRE_PREGUNTA { get; set; }
        public virtual DbSet<CODOCUR_PREGUNTA> CODOCUR_PREGUNTA { get; set; }
        public virtual DbSet<CODPRES_PREGUNTA> CODPRES_PREGUNTA { get; set; }
        public virtual DbSet<CODPTORE_PREGUNTA> CODPTORE_PREGUNTA { get; set; }
        public virtual DbSet<CONS_EXP_PREGUNTA> CONS_EXP_PREGUNTA { get; set; }
        public virtual DbSet<EDAD_MADRE_PREGUNTA> EDAD_MADRE_PREGUNTA { get; set; }
        public virtual DbSet<EMB_FAL_PREGUNTA> EMB_FAL_PREGUNTA { get; set; }
        public virtual DbSet<EMB_MES_PREGUNTA> EMB_MES_PREGUNTA { get; set; }
        public virtual DbSet<EMB_SEM_PREGUNTA> EMB_SEM_PREGUNTA { get; set; }
        public virtual DbSet<EST_CIVIL_PREGUNTA> EST_CIVIL_PREGUNTA { get; set; }
        public virtual DbSet<EST_CIVM_PREGUNTA> EST_CIVM_PREGUNTA { get; set; }
        public virtual DbSet<GRU_ED1_PREGUNTA> GRU_ED1_PREGUNTA { get; set; }
        public virtual DbSet<GRU_ED2_PREGUNTA> GRU_ED2_PREGUNTA { get; set; }
        public virtual DbSet<HORA_PREGUNTA> HORA_PREGUNTA { get; set; }
        public virtual DbSet<IDADMISALU_PREGUNTA> IDADMISALU_PREGUNTA { get; set; }
        public virtual DbSet<IDPERTET_PREGUNTA> IDPERTET_PREGUNTA { get; set; }
        public virtual DbSet<IDPROFCER_PREGUNTA> IDPROFCER_PREGUNTA { get; set; }
        public virtual DbSet<MAN_MUER_PREGUNTA> MAN_MUER_PREGUNTA { get; set; }
        public virtual DbSet<MES_PREGUNTA> MES_PREGUNTA { get; set; }
        public virtual DbSet<MINUTOS_PREGUNTA> MINUTOS_PREGUNTA { get; set; }
        public virtual DbSet<MU_PARTO_PREGUNTA> MU_PARTO_PREGUNTA { get; set; }
        public virtual DbSet<MUERTEPORO_PREGUNTA> MUERTEPORO_PREGUNTA { get; set; }
        public virtual DbSet<N_HIJOSM_PREGUNTA> N_HIJOSM_PREGUNTA { get; set; }
        public virtual DbSet<N_HIJOSV_PREGUNTA> N_HIJOSV_PREGUNTA { get; set; }
        public virtual DbSet<NIV_EDUM_PREGUNTA> NIV_EDUM_PREGUNTA { get; set; }
        public virtual DbSet<NIVEL_EDU_PREGUNTA> NIVEL_EDU_PREGUNTA { get; set; }
        public virtual DbSet<PESO_NAC_PREGUNTA> PESO_NAC_PREGUNTA { get; set; }
        public virtual DbSet<PMAN_MUER_PREGUNTA> PMAN_MUER_PREGUNTA { get; set; }
        public virtual DbSet<SEG_SOCIAL_PREGUNTA> SEG_SOCIAL_PREGUNTA { get; set; }
        public virtual DbSet<SEXO_PREGUNTA> SEXO_PREGUNTA { get; set; }
        public virtual DbSet<SIMUERTEPO_PREGUNTA> SIMUERTEPO_PREGUNTA { get; set; }
        public virtual DbSet<SIT_DEFUN_PREGUNTA> SIT_DEFUN_PREGUNTA { get; set; }
        public virtual DbSet<T_GES_PREGUNTA> T_GES_PREGUNTA { get; set; }
        public virtual DbSet<T_PARTO_PREGUNTA> T_PARTO_PREGUNTA { get; set; }
        public virtual DbSet<TIPO_EMB_PREGUNTA> TIPO_EMB_PREGUNTA { get; set; }
        public virtual DbSet<ULTCURFAL_PREGUNTA> ULTCURFAL_PREGUNTA { get; set; }
        public virtual DbSet<ULTCURMAD_PREGUNTA> ULTCURMAD_PREGUNTA { get; set; }
        public virtual DbSet<Variable> Variable { get; set; }
    }
}
